---
platform: linux
inputs:
- name: git-repo
- name: artifactory-repo
params:
  RELEASE_TYPE:
  SONATYPE_USER_TOKEN:
  SONATYPE_PASSWORD_TOKEN:
  SONATYPE_URL: ((sonatype-url))
  SONATYPE_STAGING_PROFILE_ID: ((sonatype-staging-profile-id))
  ARTIFACTORY_SERVER: ((artifactory-server))
  ARTIFACTORY_USERNAME: ((artifactory-username))
  ARTIFACTORY_PASSWORD: ((artifactory-password))
run:
  path: git-repo/ci/scripts/promote.sh
