---
platform: linux
inputs:
- name: git-repo
- name: artifactory-repo
params:
  ARTIFACTORY_USERNAME: ((artifactory-username))
  ARTIFACTORY_PASSWORD: ((artifactory-password))
run:
  path: git-repo/ci/scripts/publish-eclipse-update-site.sh
