project: spring-javaformat
branch: main
milestone: 0.0.x
github-owner: spring-io
github-repository: spring-javaformat
docker-hub-ci-organization: springci
ci-image: spring-javaformat-ci
artifactory-server: https://repo.spring.io
build-name: spring-javaformat
task-timeout: 2h00m
